on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

name: test-k8s-pipeline-latest

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    # using KinD to provide the Kubernetes instance and kubectl
    - uses: helm/kind-action@v1.5.0
      with:
        cluster_name: kind
    # setting up Tekton Pipelines, CLI and additional components...
    - uses: openshift-pipelines/setup-tektoncd@v1
      with:
        pipeline_version: latest
        feature_flags: '{}'
        cli_version: latest
        setup_registry: "true"
        patch_etc_hosts: "true"
      # pipeline-feature-flags: '{"enable-api-fields": "alpha"}'
    - name: run-tests
      run: |        
        kubectl version
        make test-e2e/kubernetes
